---
title: "Monocle2"
author: "Emeric Texeraud"
date: "20/04/2021"
output: html_notebook
---


## Installation
```{r}
BiocManager::install("monocle")
```

```{r}
library(monocle)
library(Seurat, lib.loc = "/home/labex-bioinfo/R/x86_64-pc-linux-gnu-library/diff_versions") # V4
library(scater)
```

## Create cellDataSet object
```{r}
setwd('/mnt/Data1/Raineteau/')
pal <- readRDS('CLBNxs_Neurons_without_oligo_V2.rds')

# subset Seurat object, only if needed
sub_pal <- subset(pal, idents = c("5", "6", "3", "7"))
DefaultAssay(sub_pal) <- "RNA"

cmat <- sub_pal@assays$RNA@counts
pheno <- sub_pal@meta.data
gene_short_name <- row.names(sub_pal)
feature <- as.data.frame(gene_short_name, row.names = row.names(sub_pal))

pd <- new("AnnotatedDataFrame", data = pheno)
fd <- new("AnnotatedDataFrame", data = feature)

cds <- newCellDataSet(cmat, phenoData = pd, featureData = fd, expressionFamily = negbinomial.size())
```

```{r ordercells, warning=FALSE}
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)
cds <- reduceDimension(cds, max_components = 2, reduction_method = "DDRTree")
cds <- orderCells(cds)
saveRDS(cds, file = "/mnt/Data1/Raineteau/pseudotime/pallial_monocle_neurons.rds")
```

```{r}
p <- plot_cell_trajectory(cds, color_by = "State")
p
```

```{r}
cds <- orderCells(cds, root_state = 3)
p <- plot_cell_trajectory(cds, color_by = "Pseudotime") + scale_color_viridis_c()
p
```

```{r}
diff_test_res <- differentialGeneTest(cds,
              fullModelFormulaStr = "~sm.ns(Pseudotime)")
sig_gene_names <- row.names(diff_test_res[order(diff_test_res$qval)[1:100],])
```

```{r, fig.width=7, fig.asp=1.5}
plot_pseudotime_heatmap(cds[sig_gene_names,],
                num_clusters = 3,
                cores = 1,
                show_rownames = T, return_heatmap = TRUE)
grid::grid.newpage()
```

```{r, fig.width=10, fig.asp=0.5}
cds2 <- cds[, pData(cds)$State %in% c(3, 2, 1)]
cds2@reducedDimS <- as.matrix(as.data.frame(cds2@reducedDimS)[, colnames(cds2)])

p1 <- plot_cell_trajectory(cds2, color_by = "State")
p2 <- plot_cell_trajectory(cds2, color_by = "Pseudotime") + scale_color_viridis_c()
gridExtra::grid.arrange(p1, p2, ncol = 2)
```


```{r}
diff_test_res <- differentialGeneTest(cds2,
              fullModelFormulaStr = "~sm.ns(Pseudotime)")
sig_gene_names <- row.names(diff_test_res[order(diff_test_res$qval)[1:100],])
```

```{r, fig.width=7, fig.asp=1.5}
plot_pseudotime_heatmap(cds2[sig_gene_names,],
                num_clusters = 3,
                cores = 1,
                show_rownames = T)
grid::grid.newpage()
```



```{r, fig.width=10, fig.asp=0.5}
cds3 <- cds[, pData(cds)$State %in% c(3, 2, 5)]
cds3@reducedDimS <- as.matrix(as.data.frame(cds3@reducedDimS)[, colnames(cds3)])

p1 <- plot_cell_trajectory(cds3, color_by = "State")
p2 <- plot_cell_trajectory(cds3, color_by = "Pseudotime") + scale_color_viridis_c()
gridExtra::grid.arrange(p1, p2, ncol = 2)
```

```{r}
diff_test_res <- differentialGeneTest(cds3,
              fullModelFormulaStr = "~sm.ns(Pseudotime)")
sig_gene_names <- row.names(diff_test_res[order(diff_test_res$qval)[1:100],])
```

```{r, fig.width=7, fig.asp=1.5}
plot_pseudotime_heatmap(cds3[sig_gene_names,],
                num_clusters = 3,
                cores = 1,
                show_rownames = T)
grid::grid.newpage()
```

```{r}
sub_pal <- FindVariableFeatures(sub_pal, nfeatures = 2000)

cmat <- sub_pal@assays$RNA@counts
pheno <- sub_pal@meta.data
gene_short_name <- row.names(sub_pal)
feature <- as.data.frame(gene_short_name, row.names = row.names(sub_pal))

pd <- new("AnnotatedDataFrame", data = pheno)
fd <- new("AnnotatedDataFrame", data = feature)

cds <- newCellDataSet(cmat, phenoData = pd, featureData = fd, expressionFamily = negbinomial.size())
```

```{r ordercells2, warning=FALSE}
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)
cds <- reduceDimension(cds, max_components = 2, reduction_method = "DDRTree")
cds <- orderCells(cds)
saveRDS(cds, file = "/mnt/Data1/Raineteau/pseudotime/pallial_monocle_neurons_2000genes.rds")
```

```{r}
p <- plot_cell_trajectory(cds, color_by = "State")
p
```

