---
title: "Monocle3 on pallial"
output: html_notebook
---

# Pseudotime withe Monocle 3

```{r, warning=FALSE}
library(monocle3)
library(Seurat, lib.loc = "/home/labex-bioinfo/R/x86_64-pc-linux-gnu-library/diff_versions") # V4
library(SeuratWrappers)
library(ggplot2)
library(dplyr)
```

```{r}
pal <- readRDS('/mnt/Data1/Raineteau/pal_subpal/pallial.CLB_final.rds')
Idents(pal) <- "Full_clusters"

expression_matrix <- pal@assays$RNA@counts
cell_metadata <- pal@meta.data
gene_annotation <- data.frame(gene_short_name = row.names(expression_matrix), row.names = row.names(expression_matrix))

cds <- new_cell_data_set(expression_matrix,
                         cell_metadata = cell_metadata,
                         gene_metadata = gene_annotation)
```

## preprocessing

```{r,warning=FALSE}
cds <- preprocess_cds(cds, num_dim = 20, verbose = TRUE, norm_method = "log") #attention normalisation log de monocle sur raw counts de seurat
cds = align_cds(cds, num_dim = 20, alignment_group = "Condition") #To remove batch effects between Nx1 and Nx2
cds <- reduce_dimension(cds, verbose = TRUE, preprocess_method = "Aligned", umap.min_dist = 0.2, umap.n_neighbors = 40L)

cds <- cluster_cells(cds)

cds <- learn_graph(cds, use_partition = TRUE)
```

```{r}
plot_cells(cds,
           color_cells_by = "Full_clusters",
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE)
```

```{r}
cds <- order_cells(cds)
```

```{r}
plot_cells(cds,
           color_cells_by = "pseudotime",
           label_cell_groups=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE,
           graph_label_size=1.5)
```


```{r}
saveRDS(cds, '/mnt/Data1/Raineteau/pseudotime/Monocle3_pallial_full.rds')
```


