---
title: "Seurat tutorial on public data"
author: "[LabEx CORTEX Bioinformatics Platform](https://labex-cortex.universite-lyon.fr/) - Lyon 1 University - vignette produced by Emeric Texeraud"
date: "`r Sys.Date()`"
output: html_notebook
---

## Load packages
```{r, warning=FALSE, include=TRUE}
suppressMessages({
  library(tidyverse, quietly = TRUE)
  library(Seurat, quietly = TRUE)
  library(patchwork)
  library(scater)
})
```

# 1. Overview of all cells
## Setup the Seurat Object
```{r, warning=FALSE, include=TRUE}
# Load  the public dataset
seurat_matrix <- Read10X('/mnt/Data1/public_vignettes/dataset/Bella_et_al')
seur <- CreateSeuratObject(counts = seurat_matrix, project = "Bella", min.cells = 3, min.features = 100)
seur
```


## QC and sctransform
### QC
QC metrics
```{r, fig.width=12, fig.asp=0.6, warning=FALSE, error=FALSE}
# QC metrics calculation and visualization
seur$percent.mt <- PercentageFeatureSet(seur, pattern = "^mt-")
seur$percent.ribo <- PercentageFeatureSet(seur, pattern = "^Rp[sl][[:digit:]]")
VlnPlot(seur, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.ribo"), ncol = 2, pt.size = 0)
```

```{r}
umap <- read.csv("/mnt/Data1/public_vignettes/dataset/Bella_et_al/cluster_scDevSC.merged.umap.txt", row.names = 1, sep = "\t")
umap <- umap[-1,]
umap$X <- as.numeric(umap$X)
umap$Y <- as.numeric(umap$Y)
meta <- read.csv("/mnt/Data1/public_vignettes/dataset/Bella_et_al/metaData_scDevSC.txt", row.names = 1, sep = "\t")
meta <- meta[-1,]
umap <- as.matrix(umap %>% rename(X = "orig_UMAP1", Y = "orig_UMAP2"))
umap_seur <- CreateDimReducObject(embeddings = umap, assay = "RNA", key = "orig_UMAP")
seur@reductions$orig_umap <- umap_seur 

seur@meta.data[,colnames(meta)] <- meta[Cells(seur),]
```

```{r, fig.width=10, fig.asp=.8}
DimPlot(seur, reduction = "orig_umap", group.by = "Gral_cellType")
```

```{r}
seur2 <- DietSeurat(seur, data = T, counts = F, scale.data = F, )
```


