---
title: "Seurat tutorial on Mickelsen mouse brain dataset"
author: "[LabEx CORTEX Bioinformatics Platform](https://labex-cortex.universite-lyon.fr/) - Lyon 1 University - vignette produced by Emeric Texeraud"
date: "`r Sys.Date()`"
output: html_notebook
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages
```{r, warning=FALSE, include=TRUE}
library(tidyverse, quietly = TRUE)
library(Seurat, quietly = TRUE)
library(patchwork)
library(scater)
```

## Create object

### Load both libraries 
Female library
```{r}
female.data <- Read10X(data.dir = "/mnt/Data1/public_vignettes/dataset/mickelsen_dataset/10XBatch1", strip.suffix = FALSE)
mickelsen.female <- CreateSeuratObject(counts = female.data, project = "mickelsen_Data", min.cells = 3, min.features = 200) # 3438 cells
mickelsen.female <- PercentageFeatureSet(mickelsen.female, pattern = "^mt-", col.name = "percent.mt")
VlnPlot(mickelsen.female, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

Male library
```{r}
male.data <- Read10X(data.dir = "/mnt/Data1/public_vignettes/dataset/mickelsen_dataset/10XBatch2", strip.suffix = FALSE)
mickelsen.male <- CreateSeuratObject(counts = male.data, project = "mickelsen_Data", min.cells = 3, min.features = 200) # 3793 cells
mickelsen.male <- PercentageFeatureSet(mickelsen.male, pattern = "^mt-", col.name = "percent.mt")
VlnPlot(mickelsen.male, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

### Filter cells
```{r}
mickelsen.female <-subset(mickelsen.female, subset = percent.mt<20 & nFeature_RNA>1000 & nFeature_RNA<6000 & nCount_RNA<30000) #3262 cells

mickelsen.male <-subset(mickelsen.male, subset = percent.mt<20 & nFeature_RNA>1000 & nFeature_RNA<6000 & nCount_RNA<30000) #3266 cells
```

Set Data identity for data manipulation
```{r}
mickelsen.female@meta.data$gender = "female"
mickelsen.male@meta.data$gender = "male"
```

### Merge seurat object
```{r}
mickelsen = merge(x = mickelsen.female, y = mickelsen.male, add.cell.ids = c("female", "male"), project = "merge_mickelsen")
```

## Clustering
### Preparing data
```{r, results=FALSE}
mickelsen <- FindVariableFeatures(mickelsen, assay = "RNA", verbose = FALSE)
mickelsen <- NormalizeData(mickelsen, assay = "RNA", verbose = FALSE)

mickelsen <- SCTransform(mickelsen, vars.to.regress = "percent.mt", verbose = FALSE)
```

### Choose dimension
```{r}
mickelsen <- RunPCA(mickelsen, verbose = FALSE)
ElbowPlot(mickelsen, ndims=50)
```

### calculate umap and clusters
```{r}
mickelsen <- RunUMAP(mickelsen, dims = 1:10, verbose=FALSE)
mickelsen <- FindNeighbors(mickelsen, dims = 1:10, verbose=FALSE)
mickelsen <- FindClusters(mickelsen, resolution = 0.25, verbose=FALSE) #16 clusters

DimPlot(mickelsen, pt.size = 2, label = TRUE) + NoLegend()
```


## Identification of clusters
### Markers
```{r}
markers <-FindAllMarkers(mickelsen, logfc.threshold = 1, min.pct = 0.5, verbose = FALSE, assay = "RNA", only.pos = TRUE)
top10.markers = markers %>% mutate(diff.pct = (pct.1 - pct.2)) %>% group_by(cluster) %>%
  slice_max(order_by = avg_log2FC, n = 20) %>% slice_max(order_by = diff.pct, n = 10)
top10.markers
```

```{r}
mickelsen <- RenameIdents(mickelsen, '0' = 'Neurons', '1' = 'Neurons', '2' = 'Oligos', '3' = 'Astrocytes', '4' = 'Oligos', '5' = 'Endothelial', '6' = 'OPCs', '7' = 'Neurons', '8' = 'Microglia', '9' = 'Mural', '10' = 'Oligos')

mickelsen[["cell_type"]] <- Idents(mickelsen)

DimPlot(mickelsen, pt.size = 2, label = TRUE) +NoLegend()
```

```{r}
saveRDS(mickelsen, file = "/mnt/Data1/public_vignettes/seurat_data/mickelsen.rds")
```




