---
title: "ClusterProfiler vignette"
author: "[LabEx CORTEX Bioinformatics Platform](https://labex-cortex.universite-lyon.fr/) - Lyon 1 University - vignette produced by Emeric Texeraud"
date: "`r Sys.Date()`"
output: html_notebook
---

Load libraries
```{r}
suppressMessages({
  library(tidyverse)
  library(Seurat) # Seurat V4 Required for this vignette because of avg_log2FC
  library(enrichplot)
  library(clusterProfiler)
  library(DOSE)
  library(pheatmap)
  require(org.Mm.eg.db)
  require(org.Hs.eg.db)
})
```

Set organism 
```{r}
organism = org.Mm.eg.db
```

# ORA analysis
```{r}
clb <- readRDS("/mnt/Data2/Raineteau/MarcyG_Raineteau_lab_GEO_submission_10132021/processed_data_files/dSVZ_P12_1/P12_dSVZ_Seq.rds")
Idents(clb) = "Simplified_clusters"
DefaultAssay(clb) <- "RNA"
clb_markers_ORA = FindMarkers(clb, ident.1 = "qNSCs", ident.2 = "TAPs", logfc.threshold = 0.7, assay = "RNA",verbose = FALSE)

dataORA = clb_markers_ORA
dataORA <- dataORA %>% rownames_to_column(var = "X") #To create a column gene and remove rownames
```

Filter markers of qNSCs and TAPs
```{r}
dataORA_qNSCs <- dataORA[dataORA$avg_log2FC > 0 & dataORA$p_val < 0.05,]
dataORA_TAPs <- dataORA[dataORA$avg_log2FC < 0 & dataORA$p_val < 0.05,]
```

## ORA qNSCs
```{r}
namesqNSCs <- as.character(dataORA_qNSCs$X)
egoqNSCs = bitr(namesqNSCs, fromType <- "SYMBOL", toType <- "ENTREZID", OrgDb <- "org.Mm.eg.db") #Biological Id TRanslator
geneListORA_qNSCs <- egoqNSCs$ENTREZID
```

## BP analysis qNSCs
```{r}
egoqNSCs <- enrichGO(gene          = geneListORA_qNSCs,
                  universe      = names(geneListORA_qNSCs),
                  OrgDb         = org.Mm.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.05,
                  readable      = TRUE)
```


```{r}

```

```{r}
write.csv(egoqNSCs, row.names = TRUE, file = "/home/labex-bioinfo/public_vignettes/clusterProfiler/data/ORA_qNSCs.csv")

egoqNSCs2 <- simplify(egoqNSCs, measure="Wang", semData=NULL) # The simplify method allows to remove redundant terms based on GOSemSim (select one representative term from redundant ones based on higher p.adjust, which have similarity higher than "cutoff)
write.csv(egoqNSCs2, row.names = T, file = "/home/labex-bioinfo/public_vignettes/clusterProfiler/data/ORA_qNSCs_simplify.csv")
```

```{r, fig.width=8, fig.asp=1.5}
p1 <- dotplot(egoqNSCs, x= "GeneRatio", orderBy = "GeneRatio", showCategory=25)

p2 <- dotplot(egoqNSCs2, x= "GeneRatio", orderBy = "GeneRatio", showCategory=25)

p1
p2
```


## ORA qNSCs with correct universe
```{r}
namesqNSCs <- as.character(dataORA_qNSCs$X)
egoqNSCs = bitr(namesqNSCs, fromType <- "SYMBOL", toType <- "ENTREZID", OrgDb <- "org.Mm.eg.db") #Biological Id TRanslator
univ <- bitr(row.names(clb), fromType <- "SYMBOL", toType <- "ENTREZID", OrgDb <- "org.Mm.eg.db")$ENTREZID
geneListORA_qNSCs <- egoqNSCs$ENTREZID
```


## BP analysis qNSCs
```{r}
egoqNSCs_univ <- enrichGO(gene          = geneListORA_qNSCs,
                  universe      = univ,
                  OrgDb         = org.Mm.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.05,
                  readable      = TRUE)
```

```{r, fig.asp = .6, fig.width=10}
edox <- setReadable(egoqNSCs_univ, 'org.Mm.eg.db', 'ENTREZID')
edox2 <- pairwise_termsim(edox)
p1 <- treeplot(edox2, hclust_method = "average", )
p1
```

```{r, fig.width=10, fig.asp=.5}
p1 <- emapplot(edox2, cex_line = .5, cex_category = .6, cex_label_category = .6)
p2 <- emapplot(edox2, layout="kk", cex_line = .5, cex_category = .6, cex_label_category = .6)
cowplot::plot_grid(p1, p2, ncol=2, labels=LETTERS[1:2])
```


```{r, fig.width=8, fig.asp=1.5}
p1 <- dotplot(egoqNSCs_univ, x= "GeneRatio", orderBy = "GeneRatio", showCategory=25)
p2 <- dotplot(egoqNSCs2_univ, x= "GeneRatio", orderBy = "GeneRatio", showCategory=25)

p1
p2
```

```{r, fig.asp = 1.2, fig.width=10}
edox3 <- setReadable(egoqNSCs2_univ, 'org.Mm.eg.db', 'ENTREZID')
edox32 <- pairwise_termsim(edox)
p1 <- treeplot(edox32, hclust_method = "average", )
p1
```

```{r}
gseaplot(edox2, geneSetID = 1, by = "runningScore", title = edo2$Description[1])
```


```{r}
clb_markers_GSEA <- clb_markers_ORA
df = clb_markers_GSEA
df <- df %>% rownames_to_column(var = "X")
original_gene_list <- df$avg_log2FC # we want the log2 fold change 
names(original_gene_list) <- df$X # name the vector
gene_list<-na.omit(original_gene_list) # omit any NA values
gene_list = sort(gene_list, decreasing = TRUE)
```


```{r}
gse <- gseGO(geneList=gene_list, 
             ont ="BP", 
             keyType = "SYMBOL", 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = org.Mm.eg.db, 
             pAdjustMethod = "BH")
```

```{r}
p1 <- dotplot(gse, showCategory=10, split=".sign",orderBy = "GeneRatio", x="GeneRatio") + facet_grid(.~.sign)
p2 <- gseaplot(gse, geneSetID = 1, by = "runningScore", title = gse$Description[1])
p1
p2
```

```{r}
gsex <- setReadable(gse, 'org.Mm.eg.db', 'ENTREZID')
gsex2 <- pairwise_termsim(gsex)
```


## Multi clusters : 

```{r}
clb <- readRDS("/mnt/Data2/Raineteau/MarcyG_Raineteau_lab_GEO_submission_10132021/processed_data_files/dSVZ_P12_1/P12_dSVZ_Seq.rds")
Idents(clb) = "Simplified_clusters"
DefaultAssay(clb) <- "RNA"
markers_qNSCs = FindMarkers(clb, ident.1 = "qNSCs", ident.2 = NULL, logfc.threshold = 0.5, assay = "RNA",verbose = FALSE)
markers_TAPs = FindMarkers(clb, ident.1 = "TAPs", ident.2 = NULL, logfc.threshold = 0.5, assay = "RNA",verbose = FALSE)
markers_aNSCs = FindMarkers(clb, ident.1 = "aNSCs", ident.2 = NULL, logfc.threshold = 0.5, assay = "RNA",verbose = FALSE)
markers_astro = FindMarkers(clb, ident.1 = "Astrocytes", ident.2 = NULL, logfc.threshold = 0.5, assay = "RNA",verbose = FALSE)
```

```{r}
genes_qNSCs <- bitr(row.names(markers_qNSCs[markers_qNSCs$avg_log2FC>0,]), fromType <- "SYMBOL", toType <- "ENTREZID", OrgDb <- "org.Mm.eg.db")
genes_aNSCs <- bitr(row.names(markers_aNSCs[markers_aNSCs$avg_log2FC>0,]), fromType <- "SYMBOL", toType <- "ENTREZID", OrgDb <- "org.Mm.eg.db")
genes_TAPs <- bitr(row.names(markers_TAPs[markers_TAPs$avg_log2FC>0,]), fromType <- "SYMBOL", toType <- "ENTREZID", OrgDb <- "org.Mm.eg.db")
genes_astro <- bitr(row.names(markers_astro[markers_astro$avg_log2FC>0,]), fromType <- "SYMBOL", toType <- "ENTREZID", OrgDb <- "org.Mm.eg.db")



markers <- list(qNSCs = genes_qNSCs$ENTREZID, aNSCs = genes_aNSCs$ENTREZID, TAPs = genes_TAPs$ENTREZID, Astrocytes = genes_astro$ENTREZID)
univ <- bitr(row.names(clb), fromType <- "SYMBOL", toType <- "ENTREZID", OrgDb <- "org.Mm.eg.db")$ENTREZID
```

```{r}
ck <- compareCluster(geneCluster = markers, fun = "enrichGO", OrgDb = "org.Mm.eg.db", universe = univ, ont ="BP")
ck <- setReadable(ck, OrgDb = org.Mm.eg.db, keyType="ENTREZID")
```

```{r}
ck@compareClusterResult
```


```{r}
# #Remove specific terms
# toremove = c("assembly", "cycle", "binding", "activity")
# position = unique(grep(paste(toremove,collapse="|"), ck@compareClusterResult$Description))
# ck@compareClusterResult = ck@compareClusterResult[-position, ]
dotplot(ck)
```

```{r, fig.width=10, fig.asp=0.8}
xx <- pairwise_termsim(ck)
```


```{r, fig.width=10, fig.asp=0.8}
p1 <- emapplot(xx, cex_line = 0.8, cex_category = 1.5)
p1
```

```{r, fig.width=10, fig.asp=0.8}
cnetplot(ck, showCategory = 3, node_label = "all", cex_gene = 2, cex_category = 1, cex_label_category = 1.2, cex_label_gene = 0.8)
```

```{r, fig.width=10, fig.asp=0.8}
cnetplot(ck, showCategory = 10, node_label = "category", cex_gene = 3, cex_category = 2, cex_label_category = 1.2)
```


```{r}
data("gcSample")
ck2 <- compareCluster(geneCluster = gcSample, fun = enrichKEGG)
ck2 <- setReadable(ck2, OrgDb = org.Hs.eg.db, keyType="ENTREZID")
dotplot(ck2)
```

```{r}
ck2 <- compareCluster(geneCluster = markers[c("qNSCs", "Astrocytes")], fun = "enrichKEGG")
ck2 <- setReadable(ck2, OrgDb = org.Hs.eg.db, keyType="ENTREZID")
dotplot(ck2)
```

